# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d40598619a1af7dc8c428a8e1b588b0e638b487e0da0c749212ad379260af52023d0c312af638ad9732a8d488f6bfd6ffa421c7ea885b8bebdfeff62837ed771

test:
  secret_key_base: 281fd7282d8029f10c0d494d7a4a6e9b24fe8895b3096efd5f7c33a1e2a6b5b5fcf0e35406ecaf48d7ac0da34438b68f299f9ae428f028df7ecacc235bdd6abb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
